### ISSUE TITLE
catkin build ze_vio_ceres Fails

### ISSUE THREAD

**Issue by shrutarv** [uzh-rpg/rpg_ultimate_slam_open#12]
Hello,

The build fails when I run the below command:
catkin build ze_vio_ceres
PLease have a look at the error log below:

Warnings   << ze_geometry:check /home/ghanem/uslam_ws/logs/ze_geometry/build.check.001.log                                                                                                                
CMake Warning (dev) at CMakeLists.txt:2 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

cd /home/ghanem/uslam_ws/build/ze_geometry; catkin build --get-env ze_geometry | catkin env -si  /usr/bin/make cmake_check_build_system; cd -

..........................................................................................................................................................................................................
__________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << imp_features:make /home/ghanem/uslam_ws/logs/imp_features/build.make.004.log                                                                                                                
In file included from /home/ghanem/uslam_ws/src/rpg_ultimate_slam_open/imp/imp_features/src/fast_masked_sse.cpp:1:
/home/ghanem/uslam_ws/src/rpg_ultimate_slam_open/imp/imp_features/include/imp/features/fast_masked.hpp:3:10: fatal error: fast/fast.h: No such file or directory
    3 | #include <fast/fast.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/imp_features.dir/build.make:128: CMakeFiles/imp_features.dir/src/fast_masked_sse.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/ghanem/uslam_ws/src/rpg_ultimate_slam_open/imp/imp_features/src/fast_detector.cpp:4:10: fatal error: fast/fast.h: No such file or directory
    4 | #include <fast/fast.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/imp_features.dir/build.make:63: CMakeFiles/imp_features.dir/src/fast_detector.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1106: CMakeFiles/imp_features.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /home/ghanem/uslam_ws/build/imp_features; catkin build --get-env imp_features | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

..........................................................................................................................................................................................................
Failed     << imp_features:make                 [ Exited with code 2 ]                                                                                                                                    
Failed    <<< imp_features                      [ 4.8 seconds ]                                                                                                                                           
Abandoned <<< imp_correspondence                [ Unrelated job failed ]                                                                                                                                  
Abandoned <<< ze_vio_common                     [ Unrelated job failed ]                                                                                                                                  
Abandoned <<< ze_ceres_backend                  [ Unrelated job failed ]                                                                                                                                  
Abandoned <<< ze_data_provider                  [ Unrelated job failed ]                                                                                                                                  
Abandoned <<< ze_vio_frontend                   [ Unrelated job failed ]                                                                                                                                  
Abandoned <<< ze_vio_ceres                      [ Unrelated job failed ]                                                                                                                                  
Finished  <<< ze_visualization                  [ 10.7 seconds ]                                                                                                                                          
Finished  <<< ze_geometry                       [ 9.4 seconds ]                                                                                                                                           
[build] Summary: 21 of 28 packages succeeded.                                                                                                                                                             
[build]   Ignored:   13 packages were skipped or are skiplisted.                                                                                                                                          
[build]   Warnings:  12 packages succeeded with warnings.                                                                                                                                                 
[build]   Abandoned: 6 packages were abandoned.                                                                                                                                                           
[build]   Failed:    1 packages failed.                                                                                                                                                                   
[build] Runtime: 41.0 seconds total.

**Comment by OnurSelim** [comment]
Hi! How did solve this problem?
